var nme = " Shiva ";
var platfrom = "Java";
console.log("-------------------");
console.log("Trainer Details:");
console.log("-------------------");
console.log("Name Of Trainer:" + nme + "\nTainer Of :" + platfrom);
var train = [2, "Muthu", "Trainer"];
console.log(train);
console.log("Adding JavaPlatfrom:");
train.push("java");
console.log(train);
console.log("Removing JavaPlatfrom:");
train.splice(3);
console.log(train);
