var wid = 25.25, len = 96.2, heig = 56.9, a = 28.36;
console.log("Area of Square");
console.log("--------------");
var square = a * a;
var sq = square.toFixed(2);
console.log("Suraface Area : " + sq);
console.log("--------------");
console.log("Area of Rectangle");
console.log("----------------");
var rec = wid * heig;
var rt = rec.toFixed(2);
console.log("Suraface Area : " + rt);
console.log("--------------");
console.log("Area of Triangle");
console.log("----------------");
var tri = wid * heig / 2;
var tr = tri.toFixed(2);
console.log("Suraface Area : " + tr);
